### ISSUE TITLE
[Feature Request] Support MDX Compilation

### ISSUE THREAD

**Issue by CHC383** [storybookjs/vite-plugin-storybook-nextjs#29]
Original bug reporting: https://github.com/storybookjs/storybook/issues/29707

It seems that MDX compilation is not supported by vite-plugin-storybook-nextjs, this is a feature request to integrate vite-plugin-storybook-nextjs with mdx-js (similar to [Next.JS integration](https://nextjs.org/docs/pages/building-your-application/configuring/mdx)) so that users can run Storybook test on MDX components via Vitest.

A workaround to test the MDX component through Vitest directly is listed [below](https://github.com/storybookjs/vite-plugin-storybook-nextjs/issues/29#issuecomment-2529271700), but it would still be better to test the component directly through Storybook to combine with visual testing and avoid extra testing code.

**Comment by CHC383** [comment]
@valentinpalkovic I wonder if you could shed any light here, maybe MDX is not supported by [vite-plugin-storybook-nextjs](https://github.com/storybookjs/vite-plugin-storybook-nextjs) at the moment (as I don't see `src/plugins/next-mdx`)?

**Comment by CHC383** [comment]
Rendering MDX requires compilation from MDX to js using [mdxjs](https://mdxjs.com/docs/getting-started), Next.js has [integration with MDX](https://nextjs.org/docs/pages/building-your-application/configuring/mdx) to handle the compilation, but it seems [vite-plugin-storybook-nextjs](https://github.com/storybookjs/vite-plugin-storybook-nextjs) doesn't have the integration yet.

A workaround I found to unit test MDX component is to use Vitest directly with mdx-js integration. For example

```typescript
// vitest.config.ts
// Vitest uses Rollup (https://rollupjs.org/) as the bundler
import mdx from "@mdx-js/rollup";
import { defineConfig } from "vitest/config";

export default defineConfig({
    plugins: [
        // ..., 
        mdx()
    ],
    // ...
});
```

```typescript
// page.tsx
import Content from "<path-to-mdx>/content.mdx";

export default function Page() {
  return <Content />;
}
```

```typescript
// page.test.tsx
import { MDXProvider } from "@mdx-js/react";
import { render, screen } from "@testing-library/react";

import Page from "<path-to-page>/page";

describe("page", () => {
    test("renders", () => {
        const page = Page();
        render(<MDXProvider>{page}</MDXProvider>);
        expect(screen.getByText("xxx")).toBeInTheDocument();
    });
});
```

**Comment by CHC383** [comment]
Inspired by https://github.com/storybookjs/vite-plugin-storybook-nextjs/issues/29#issuecomment-2529271700, I added the `@mdx-js/rollup` plugins to the plugin list of storybook vitest config, and the portable stories is now able to handle the MDX components.

```typescript
// vitest.config.ts
// Vitest uses Rollup (https://rollupjs.org/) as the bundler
import mdx from "@mdx-js/rollup";

export default xxx({
    // plugin list for storybook, no matter it is in a separate config, MergeConfig in vitest.config.ts, or in vitest.workspace.ts
    plugins: [
        // ..., 
        mdx()
    ],
    // ...
});
```

**Comment by chris-erickson** [comment]
What should one do if hitting this issue without using MDX, and the suggested fixes here don't help?

**Comment by CHC383** [comment]
> What should one do if hitting this issue without using MDX, and the suggested fixes here don't help?

Please share more details as I did in https://github.com/storybookjs/storybook/issues/29707, so that others could understand your setup, and ideally a minimum reproduction. Since you are not using MDX, it is likely that you use something else that can't be compiled/transformed by SWC and Rollup, I would suggest to create a different issue, and at the end the solution might be finding an existing Vite/Vitest plugin that handles it, or make a feature request somewhere.

**Comment by valentinpalkovic** [comment]
Hi @CHC383 

Thank you for the bug report, and I apologize for the late response.

It is fantastic that you found a solution. Indeed, we don't want to built-in MDX support to keep the package size small. The plugin itself should be used either as part of Storybook (where MDX is handled separately) or in a unit test environment with Vitest. Usually, people test their pure components/stories in Vitest, which doesn't include MDX. In your case, a separate MDX plugin is necessary.
